spring.application.name=vanOpt

spring.datasource.url=jdbc:postgresql://localhost:5432/vanopt
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# ვინაიდან Flyway-ს ვიყენებთ, Hibernate-ს ვეუბნებით რომ თვითონ არ შექმნას ცხრილები (validate)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway კონფიგურაცია
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration